version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - monitor_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor_net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitor_net

networks:
  monitor_net:
